name       : goffice0.8
version    : 0.8.17
release    : 4
source     :
    - https://ftp.gnome.org/pub/gnome/sources/goffice/0.8/goffice-0.8.17.tar.xz : 165070beb67b84580afe80a8a100b674a81d553ab791acd72ac0c655f4fadb15
license    : GPL-2.0-only
component  : office
summary    : The GOffice package contains a library of GLib/GTK document centric objects and utilities
description: |
    The GOffice package contains a library of GLib/GTK document centric objects and utilities.
builddeps  :
    - pkgconfig(cairo-svg)
    - pkgconfig(libgsf-1)
    - pkgconfig(gtk+-2.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
